name: 'Pull Request Metadata'
description: 'Greet someone and record the time'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
  token:
    description: 'The token to use to access the GitHub API'
    required: true
outputs:
  state: # New state
    description: 'New state of PR'
runs:
  using: 'node16'
  main: 'dist/index.js'