name: PR metadata annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize, closed, labeled, review_requested]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    outputs:
      state: ${{ steps.annotate-pr.outputs.state }}
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Annotate PR
        uses: 7Mountains/ga-pr-metadata@main
        id: annotate-pr
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'