name: PR metadata annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize, closed, labeled]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    outputs:
      state: ${{ steps.annotate-pr.outputs.state }}
    steps:
      - name: Annotate PR
        uses: 7Mountains/ga-pr-metadata@main
        id: annotate-pr
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}