name: PR slack notification
on: [push]
jobs:

  notify-slack:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    name: Notifies slack channel about push event
    outputs:
      state: ${{ steps.notify-slack.outputs.state }}
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                text: `version deployed to \`${process.env.AS_REF}\`. <https://bit.ly/3rYNiVZ|Release notes>`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
